### ISSUE TITLE
Multi-platform

### ISSUE THREAD

**Issue by Revadike** [xMistt/DeviceAuthGenerator#1]
Could you perhaps pre-compile DeviceAuthGenerator for platforms other than Windows? Thanks

Btw, I adopted this auth tool for my project https://github.com/Revadike/epicgames-freebies-claimer. Much appreciated!

**Comment by xMistt** [comment]
Of course I can & glad I helped. :)

**Comment by Revadike** [comment]
Also, what method did you use to compile it? It may be useful for people that don't trust pre-compiled binaries.

**Comment by xMistt** [comment]
pyinstaller and just default arguments to compile "generator.py", ill add instructions on how to compile on the readme
