### ISSUE TITLE
Program not working

### ISSUE THREAD

**Issue by Minty64** [xMistt/DeviceAuthGenerator#7]
When I open the .exe the file redirects us but website only asks to authorize and not any code, this is the error on the program- `
{
    "errorCode": "errors.com.epicgames.common.oauth.invalid_token",
    "errorMessage": "Client id mismatch in credentials for this pin grant",
    "messageVars": [],
    "numericErrorCode": 1012,
    "originatingService": "com.epicgames.account.public",
    "intent": "prod",
    "error_description": "Client id mismatch in credentials for this pin grant",
    "error": "invalid_grant"
}` 
![image](https://user-images.githubusercontent.com/57541059/133199701-c1d49c4a-3a6e-4ada-839f-7651eb99bf3d.png)

**Comment by fatinghenji** [comment]
How did you solve this problem?
